# Generated by Django 3.2.7 on 2021-09-16 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=128)),
                ('umur', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('tb', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('penyakit', models.CharField(max_length=40)),
                ('diabetes', models.BooleanField()),
                ('jantung', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
